version: "2"

linters:
  default: none
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Go vet
    - staticcheck   # Static analysis
    - unused        # Unused code
    - ineffassign   # Ineffective assignments
    - misspell      # Spelling mistakes
    - revive        # Fast, configurable linter

  settings:
    errcheck:
      check-type-assertions: true
    staticcheck:
      checks: ["all"]
    unused:
      check-exported: false

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck  # Allow unchecked errors in tests

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
