version: 2

linters-settings:
  errcheck:
    check-type-assertions: true
  staticcheck:
    checks: ["all"]
  unused:
    check-exported: false

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Go vet
    - staticcheck   # Static analysis
    - unused        # Unused code
    - ineffassign   # Ineffective assignments
    - misspell      # Spelling mistakes
    - revive        # Fast, configurable linter

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck  # Allow unchecked errors in tests

